// giscus 댓글창을 사이트의 숲 캠프 팔레트(tokens.css)로 칠하는 테마 CSS 를 만든다.
// tokens.css 의 색을 바꿨으면 `node scripts/giscus-theme.mjs` 로 다시 생성.
import { mkdirSync, writeFileSync } from 'node:fs';

const schemes = {
  light: {
    primary: '#4d7c3a', onPrimary: '#f4fbef', primaryContainer: '#e1ead9', onPrimaryContainer: '#203a1a',
    secondaryContainer: '#e6ece1', onSecondaryContainer: '#1f2d24', tertiary: '#d9781f',
    error: '#c2413b', errorContainer: '#f7dcd9',
    surface: '#f4f6f1', onSurface: '#15201a', onSurfaceVariant: '#5d6d62',
    low: '#ffffff', container: '#ebf0e7', high: '#e6ece1', highest: '#dbe3d6',
    outline: '#8a998f', outlineVariant: '#d9e1d3', success: '#4d7c3a', attention: '#b8651a',
  },
  dark: {
    primary: '#7fae68', onPrimary: '#0c150e', primaryContainer: '#1c2a21', onPrimaryContainer: '#d7ecc9',
    secondaryContainer: '#1b2720', onSecondaryContainer: '#e6eee8', tertiary: '#f0a13a',
    error: '#e0605a', errorContainer: '#4a1a18',
    surface: '#0d1511', onSurface: '#e6eee8', onSurfaceVariant: '#95a59b',
    low: '#131d17', container: '#17221b', high: '#1b2720', highest: '#223029',
    outline: '#5f7266', outlineVariant: '#223029', success: '#86b36f', attention: '#f0a13a',
  },
};

const css = (c, dark) => `/* Generated by scripts/giscus-theme.mjs — Forest camp ${dark ? 'dark' : 'light'} */
@import url('https://giscus.app/themes/${dark ? 'dark' : 'light'}.css');

main {
  --color-fg-default: ${c.onSurface};
  --color-fg-muted: ${c.onSurfaceVariant};
  --color-fg-subtle: ${c.outline};
  --color-canvas-default: ${c.surface};
  --color-canvas-overlay: ${c.high};
  --color-canvas-inset: ${c.low};
  --color-canvas-subtle: ${c.container};
  --color-border-default: ${c.outlineVariant};
  --color-border-muted: ${c.outlineVariant};
  --color-neutral-muted: ${c.highest};
  --color-accent-fg: ${c.primary};
  --color-accent-emphasis: ${c.primary};
  --color-accent-muted: ${c.primaryContainer};
  --color-accent-subtle: ${c.primaryContainer};
  --color-success-fg: ${c.success};
  --color-attention-fg: ${c.attention};
  --color-danger-fg: ${c.error};
  --color-danger-subtle: ${c.errorContainer};

  --color-btn-text: ${c.onSecondaryContainer};
  --color-btn-bg: ${c.secondaryContainer};
  --color-btn-border: transparent;
  --color-btn-shadow: none;
  --color-btn-inset-shadow: none;
  --color-btn-hover-bg: ${c.highest};
  --color-btn-hover-border: transparent;
  --color-btn-active-bg: ${c.highest};
  --color-btn-active-border: transparent;
  --color-btn-selected-bg: ${c.secondaryContainer};
  --color-btn-primary-text: ${c.onPrimary};
  --color-btn-primary-bg: ${c.primary};
  --color-btn-primary-border: transparent;
  --color-btn-primary-shadow: none;
  --color-btn-primary-inset-shadow: none;
  --color-btn-primary-hover-bg: ${c.primary};
  --color-btn-primary-hover-border: transparent;
  --color-btn-primary-selected-bg: ${c.primary};
  --color-btn-primary-disabled-text: ${c.onSurfaceVariant};
  --color-btn-primary-disabled-bg: ${c.highest};
  --color-btn-primary-disabled-border: transparent;
  --color-segmented-control-bg: ${c.container};
  --color-segmented-control-button-bg: ${c.surface};
  --color-segmented-control-button-selected-border: ${c.outlineVariant};
  --color-action-list-item-default-hover-bg: ${c.high};
  --color-scale-gray-1: ${c.high};
  --color-scale-blue-1: ${c.primaryContainer};
  --color-social-reaction-bg-hover: ${c.high};
  --color-social-reaction-bg-reacted-hover: ${c.primaryContainer};
  --color-primer-shadow-inset: none;

  font-family: 'Pretendard Variable', Pretendard, 'Noto Sans KR', system-ui, sans-serif;
}

/* 둥근 카드, 알약형 버튼 */
main .gsc-comment-box,
main .gsc-comment > div,
main .gsc-reply-box { border-radius: 12px; }
main .gsc-comment-box-tabs { border-radius: 12px 12px 0 0; }
main .gsc-comment-box-textarea { border-radius: 8px; }
main .btn { border-radius: 999px; font-weight: 500; padding-inline: 20px; }
main .gsc-direct-reaction-button,
main .gsc-social-reaction-summary-item { border-radius: 8px; }
main .gsc-social-reaction-summary-item.has-reacted { background: ${c.secondaryContainer}; color: ${c.onSecondaryContainer}; }
main .gsc-comment-author-avatar img,
main .gsc-reply-author-avatar img { border-radius: 999px; }
main a:not(.btn) { color: ${c.primary}; }
`;

mkdirSync('public/giscus', { recursive: true });
for (const [name, c] of Object.entries(schemes)) writeFileSync(`public/giscus/${name}.css`, css(c, name === 'dark'));
console.log('public/giscus/{light,dark}.css 생성');
