// giscus 댓글창을 사이트의 M3 토큰으로 칠하는 테마 CSS 를 만든다.
// tokens.css 의 색을 바꿨으면 `node scripts/giscus-theme.mjs` 로 다시 생성.
import { mkdirSync, writeFileSync } from 'node:fs';

const schemes = {
  light: {
    primary: '#6750a4', onPrimary: '#ffffff', primaryContainer: '#eaddff', onPrimaryContainer: '#4f378b',
    secondaryContainer: '#e8def8', onSecondaryContainer: '#4a4458', tertiary: '#7d5260',
    error: '#b3261e', errorContainer: '#f9dedc',
    surface: '#fef7ff', onSurface: '#1d1b20', onSurfaceVariant: '#49454f',
    low: '#f7f2fa', container: '#f3edf7', high: '#ece6f0', highest: '#e6e0e9',
    outline: '#79747e', outlineVariant: '#cac4d0', success: '#386a20', attention: '#7c5800',
  },
  dark: {
    primary: '#d0bcff', onPrimary: '#381e72', primaryContainer: '#4f378b', onPrimaryContainer: '#eaddff',
    secondaryContainer: '#4a4458', onSecondaryContainer: '#e8def8', tertiary: '#efb8c8',
    error: '#f2b8b5', errorContainer: '#8c1d18',
    surface: '#141218', onSurface: '#e6e0e9', onSurfaceVariant: '#cac4d0',
    low: '#1d1b20', container: '#211f26', high: '#2b2930', highest: '#36343b',
    outline: '#938f99', outlineVariant: '#49454f', success: '#9cd67d', attention: '#f5bf48',
  },
};

const css = (c, dark) => `/* Generated by scripts/giscus-theme.mjs — Material 3 ${dark ? 'dark' : 'light'} */
@import url('https://giscus.app/themes/${dark ? 'dark' : 'light'}.css');

main {
  --color-fg-default: ${c.onSurface};
  --color-fg-muted: ${c.onSurfaceVariant};
  --color-fg-subtle: ${c.outline};
  --color-canvas-default: ${c.surface};
  --color-canvas-overlay: ${c.high};
  --color-canvas-inset: ${c.low};
  --color-canvas-subtle: ${c.container};
  --color-border-default: ${c.outlineVariant};
  --color-border-muted: ${c.outlineVariant};
  --color-neutral-muted: ${c.highest};
  --color-accent-fg: ${c.primary};
  --color-accent-emphasis: ${c.primary};
  --color-accent-muted: ${c.primaryContainer};
  --color-accent-subtle: ${c.primaryContainer};
  --color-success-fg: ${c.success};
  --color-attention-fg: ${c.attention};
  --color-danger-fg: ${c.error};
  --color-danger-subtle: ${c.errorContainer};

  --color-btn-text: ${c.onSecondaryContainer};
  --color-btn-bg: ${c.secondaryContainer};
  --color-btn-border: transparent;
  --color-btn-shadow: none;
  --color-btn-inset-shadow: none;
  --color-btn-hover-bg: ${c.highest};
  --color-btn-hover-border: transparent;
  --color-btn-active-bg: ${c.highest};
  --color-btn-active-border: transparent;
  --color-btn-selected-bg: ${c.secondaryContainer};
  --color-btn-primary-text: ${c.onPrimary};
  --color-btn-primary-bg: ${c.primary};
  --color-btn-primary-border: transparent;
  --color-btn-primary-shadow: none;
  --color-btn-primary-inset-shadow: none;
  --color-btn-primary-hover-bg: ${c.primary};
  --color-btn-primary-hover-border: transparent;
  --color-btn-primary-selected-bg: ${c.primary};
  --color-btn-primary-disabled-text: ${c.onSurfaceVariant};
  --color-btn-primary-disabled-bg: ${c.highest};
  --color-btn-primary-disabled-border: transparent;
  --color-segmented-control-bg: ${c.container};
  --color-segmented-control-button-bg: ${c.surface};
  --color-segmented-control-button-selected-border: ${c.outlineVariant};
  --color-action-list-item-default-hover-bg: ${c.high};
  --color-scale-gray-1: ${c.high};
  --color-scale-blue-1: ${c.primaryContainer};
  --color-social-reaction-bg-hover: ${c.high};
  --color-social-reaction-bg-reacted-hover: ${c.primaryContainer};
  --color-primer-shadow-inset: none;

  font-family: 'Roboto Flex', 'Roboto', 'Noto Sans KR', system-ui, sans-serif;
}

/* M3 셰이프: 카드 12px, 버튼·반응 칩은 pill */
main .gsc-comment-box,
main .gsc-comment > div,
main .gsc-reply-box { border-radius: 12px; }
main .gsc-comment-box-tabs { border-radius: 12px 12px 0 0; }
main .gsc-comment-box-textarea { border-radius: 8px; }
main .btn { border-radius: 999px; font-weight: 500; padding-inline: 20px; }
main .gsc-direct-reaction-button,
main .gsc-social-reaction-summary-item { border-radius: 8px; }
main .gsc-social-reaction-summary-item.has-reacted { background: ${c.secondaryContainer}; color: ${c.onSecondaryContainer}; }
main .gsc-comment-author-avatar img,
main .gsc-reply-author-avatar img { border-radius: 999px; }
main a:not(.btn) { color: ${c.primary}; }
`;

mkdirSync('public/giscus', { recursive: true });
for (const [name, c] of Object.entries(schemes)) writeFileSync(`public/giscus/${name}.css`, css(c, name === 'dark'));
console.log('public/giscus/{light,dark}.css 생성');
