// giscus 댓글창을 사이트의 JINY 보라 팔레트(tokens.css)로 칠하는 테마 CSS 를 만든다.
// tokens.css 의 색을 바꿨으면 `node scripts/giscus-theme.mjs` 로 다시 생성.
import { mkdirSync, writeFileSync } from 'node:fs';

const schemes = {
  light: {
    primary: '#6d5ce7', onPrimary: '#ffffff', primaryContainer: '#ece8ff', onPrimaryContainer: '#3b2f99',
    secondaryContainer: '#efedf7', onSecondaryContainer: '#221f3a', tertiary: '#e0508f',
    error: '#d23b5f', errorContainer: '#fbe3ea',
    surface: '#f7f6fb', onSurface: '#17152a', onSurfaceVariant: '#67627f',
    low: '#ffffff', container: '#f0eef7', high: '#efedf7', highest: '#e4e1ef',
    outline: '#8e89a6', outlineVariant: '#e4e1ef', success: '#4fa82a', attention: '#d99a00',
  },
  dark: {
    primary: '#a594ff', onPrimary: '#120f24', primaryContainer: '#211d33', onPrimaryContainer: '#ddd6ff',
    secondaryContainer: '#1c1a28', onSecondaryContainer: '#eceaf6', tertiary: '#ff6fae',
    error: '#ff6f8e', errorContainer: '#4a1a28',
    surface: '#0c0b12', onSurface: '#eceaf6', onSurfaceVariant: '#9d98b3',
    low: '#14121d', container: '#191724', high: '#1c1a28', highest: '#252233',
    outline: '#6a6582', outlineVariant: '#252233', success: '#b6f36b', attention: '#ffd84a',
  },
};

const css = (c, dark) => `/* Generated by scripts/giscus-theme.mjs — JINY purple ${dark ? 'dark' : 'light'} */
@import url('https://giscus.app/themes/${dark ? 'dark' : 'light'}.css');

main {
  --color-fg-default: ${c.onSurface};
  --color-fg-muted: ${c.onSurfaceVariant};
  --color-fg-subtle: ${c.outline};
  --color-canvas-default: ${c.surface};
  --color-canvas-overlay: ${c.high};
  --color-canvas-inset: ${c.low};
  --color-canvas-subtle: ${c.container};
  --color-border-default: ${c.outlineVariant};
  --color-border-muted: ${c.outlineVariant};
  --color-neutral-muted: ${c.highest};
  --color-accent-fg: ${c.primary};
  --color-accent-emphasis: ${c.primary};
  --color-accent-muted: ${c.primaryContainer};
  --color-accent-subtle: ${c.primaryContainer};
  --color-success-fg: ${c.success};
  --color-attention-fg: ${c.attention};
  --color-danger-fg: ${c.error};
  --color-danger-subtle: ${c.errorContainer};

  --color-btn-text: ${c.onSecondaryContainer};
  --color-btn-bg: ${c.secondaryContainer};
  --color-btn-border: transparent;
  --color-btn-shadow: none;
  --color-btn-inset-shadow: none;
  --color-btn-hover-bg: ${c.highest};
  --color-btn-hover-border: transparent;
  --color-btn-active-bg: ${c.highest};
  --color-btn-active-border: transparent;
  --color-btn-selected-bg: ${c.secondaryContainer};
  --color-btn-primary-text: ${c.onPrimary};
  --color-btn-primary-bg: ${c.primary};
  --color-btn-primary-border: transparent;
  --color-btn-primary-shadow: none;
  --color-btn-primary-inset-shadow: none;
  --color-btn-primary-hover-bg: ${c.primary};
  --color-btn-primary-hover-border: transparent;
  --color-btn-primary-selected-bg: ${c.primary};
  --color-btn-primary-disabled-text: ${c.onSurfaceVariant};
  --color-btn-primary-disabled-bg: ${c.highest};
  --color-btn-primary-disabled-border: transparent;
  --color-segmented-control-bg: ${c.container};
  --color-segmented-control-button-bg: ${c.surface};
  --color-segmented-control-button-selected-border: ${c.outlineVariant};
  --color-action-list-item-default-hover-bg: ${c.high};
  --color-scale-gray-1: ${c.high};
  --color-scale-blue-1: ${c.primaryContainer};
  --color-social-reaction-bg-hover: ${c.high};
  --color-social-reaction-bg-reacted-hover: ${c.primaryContainer};
  --color-primer-shadow-inset: none;

  font-family: 'Pretendard Variable', Pretendard, 'Noto Sans KR', system-ui, sans-serif;
}

/* 둥근 카드, 알약형 버튼 */
main .gsc-comment-box,
main .gsc-comment > div,
main .gsc-reply-box { border-radius: 12px; }
main .gsc-comment-box-tabs { border-radius: 12px 12px 0 0; }
main .gsc-comment-box-textarea { border-radius: 8px; }
main .btn { border-radius: 999px; font-weight: 500; padding-inline: 20px; }
main .gsc-direct-reaction-button,
main .gsc-social-reaction-summary-item { border-radius: 8px; }
main .gsc-social-reaction-summary-item.has-reacted { background: ${c.secondaryContainer}; color: ${c.onSecondaryContainer}; }
main .gsc-comment-author-avatar img,
main .gsc-reply-author-avatar img { border-radius: 999px; }
main a:not(.btn) { color: ${c.primary}; }
`;

mkdirSync('public/giscus', { recursive: true });
for (const [name, c] of Object.entries(schemes)) writeFileSync(`public/giscus/${name}.css`, css(c, name === 'dark'));
console.log('public/giscus/{light,dark}.css 생성');
